### ISSUE TITLE
[FEATURE] Added content stays after refresh

### ISSUE THREAD

**Issue by YuriDevAT** [YurisCodingClub/html-tag-quiz#10]
### Description

As a user I want the added input to be shown in the list even when refreshing the page.

**Acceptance Criteria (AC):**
- [ ] When adding a new tag in the list, the tag is still visible in the list after refreshing the page

### Screenshots
Adding some tags
![A list with 3 items](https://github.com/YurisCodingClub/html-tag-quiz/assets/54622834/16b22cc0-db2e-423a-ab71-8213b22e2b81)

After hitting the refresh button
![A list with the initial item](https://github.com/YurisCodingClub/html-tag-quiz/assets/54622834/f75dbc1c-8978-4d81-b63d-3ce686b4ffeb)

**Comment by parthkasture** [comment]
I would like to contribute on this issue.

**Comment by CorinaMurg** [comment]
I am interested in this issue, if still available. It would be great to give it priority because it would help having the list visible as we are managing and testing additional features. 🙏
