### ISSUE TITLE
[FEATURE] Only add tags from the list

### ISSUE THREAD

**Issue by YuriDevAT** [YurisCodingClub/html-tag-quiz#11]
### Description

As a user I want to only be able to add tags which are contained in the list.

**Acceptance Criteria (AC)**
- [ ] When hitting the submit button, the tag only gets added to the list if it part of the array from the index.js file

**Comment by CorinaMurg** [comment]
Hi Julia,
I'm interested in working on this issue. 
Many thanks! 
Corina
