### ISSUE TITLE
[FEATURE] Prevent duplication of tags

### ISSUE THREAD

**Issue by YuriDevAT** [YurisCodingClub/html-tag-quiz#12]
### Description

As a user, I want to add an html tag only once.

**Acceptance criteria (AC)**
- [ ] When I want to submit a tag which is already in the list, the tag should not be added to the list

### Screenshots
![A list with a three times](https://github.com/YurisCodingClub/html-tag-quiz/assets/54622834/ce027157-b4fa-4da3-88b0-aefd6f46e22d)

### Additional information

Future task could be adding an error message. But will be decided when the app progresses.

**Comment by saffi-786** [comment]
Hey @YuriDevAT, I would like to work on this issue. Please assign me this issue.

**Comment by parthkasture** [comment]
I would like to contribute on this issue.
