### ISSUE TITLE
[ENHANCEMENT] Simple Regex - Follow Up #14

### ISSUE THREAD

**Issue by YuriDevAT** [YurisCodingClub/html-tag-quiz#15]
### Description

As suggested by @CorinaMurg in [PR#14](https://github.com/YurisCodingClub/html-tag-quiz/pull/14) following enhancement should be made to the user input:

- [ ] Trimming unnecessary white spaces at the beginning and/or end of the input.
- [ ] Ensuring case-insensitive matching.
- [ ] Stripping off any inclusion of angle brackets, or non-alphabetic characters in general.

**Comment by CorinaMurg** [comment]
I would love to work on this one, if available! 🙏
