### ISSUE TITLE
[ENHANCEMENT] create import for tags to use them in the function

### ISSUE THREAD

**Issue by YuriDevAT** [YurisCodingClub/html-tag-quiz#17]
### Description

To ensure code quality let's keep the files neat and clean.

**Acceptance criteria**

- [ ] Remove the tag list from the index.js file
- [ ] import the tag array to use it in the function

**Comment by Vvinathi** [comment]
Hi, would like to try solving this issue, by moving the 'tags' list to 'tags.js' and then importing it into 'index.js' for cleaner and more organized code?

**Comment by FreemRL** [comment]
Hey I would like to work on this. Please assign me when needed :)

**Comment by YuriDevAT** [comment]
Sure @FreemRL please go ahead.
