### ISSUE TITLE
[FEATURE] Create array with all html tags

### ISSUE THREAD

**Issue by YuriDevAT** [YurisCodingClub/html-tag-quiz#2]
### Description

In the `index.js` file create an array with all html tags and store the value to a variable called **tags**.

**Example:**

const tags = ["section", "h1", "p", ...]

**Comment by RachitGarg-12** [comment]
@YuriDevAT  I wanna contribute to this.

**Comment by TiffanyClark** [comment]
I like to work on this. please add me

**Comment by octosapien** [comment]
I was really hoping to be able to contribute to this.
Would it be possible for you to assign me this ?

**Comment by YuriDevAT** [comment]
@octosapien Thank you for your interest contributing to the project. This particular issue is already assigned to someone else.
