### ISSUE TITLE
[ENHANCEMENT] Clear input field

### ISSUE THREAD

**Issue by YuriDevAT** [YurisCodingClub/html-tag-quiz#22]
### Description

As a user, I want the input field to be cleared after adding a new tag. In case, the tag is already in the list, the input field should not be cleared but the content should stay to show the user that the input cannot be added to the list.

### Additional information

The issue may interferes with issue #12

**Comment by Abhishek7Tech** [comment]
Hi @YuriDevAT I would like to contribute.

**Comment by ArslanYM** [comment]
@YuriDevAT Can I work on this?
