### ISSUE TITLE
[FEATURE] Heading and Subheading

### ISSUE THREAD

**Issue by YuriDevAT** [YurisCodingClub/html-tag-quiz#23]
### Description

As a user, I want to understand what the application is about by reading the heading and subheading.

**Acceptance criteria**

- [ ] Create a clear heading that makes clear what the app is about
- [ ] Create a short introduction as a subheading to explain what the user has to do

**Note:** The app is a quiz. The user adds all html tags which they know. The tags list contains outdated ones as well.

### Screenshots

![Heading and subheading saying Semantic HTML tags, how many do you know?](https://github.com/YurisCodingClub/html-tag-quiz/assets/54622834/187192cc-a995-4412-be0f-5609fe4fbeaa)

**Comment by Abhishek7Tech** [comment]
Hi @YuriDevAT I would like to contribute.

**Comment by YuriDevAT** [comment]
Hi @Abhishek7Tech as mentioned via labels, the ticket is currently not ready to work on.

**Comment by CorinaMurg** [comment]
Working on this right now. Should we have also an About page? Maybe briefly talking about the importance of semantic html, and a guide on how to use the app. That might change how detailed the subtitle needs to be. Just a thought!

**Comment by CorinaMurg** [comment]
I have this in a Google doc, but maybe it's easier to keep everything together.
Here are my suggestions so far. I am not attached to either one of them, so open to making any adjustments.

Title Suggestion 1: 
HTML Tag Quiz
Title Suggestion 2: (works with suggestion 3)
Tagged! The HTML Quiz

Subtitle Suggestion 1:
A Web Developer's Test of Semantic HTML.
Enter one tag at a time and see how many you can recall!
About OR Instructions OR User Guide

Subtitle  Suggestion 2: 
Put your web knowledge to the test and discover how well you know your tags.
Add tags to your list one at a time.
About OR Instructions OR User Guide

Subtitle  Suggestion 3: (works with Title 2)
The ultimate challenge for web developers. Tag, you're it!
About OR Instructions OR User Guide

**Comment by YuriDevAT** [comment]
I like the last one 😃 : 
<h1>Tagged! The HTML Quiz</h1>
<h2>The ultimate challenge for web developers. Tag, you're it!</h2>

**Comment by CorinaMurg** [comment]
Then have the label of the input say something like: "Enter one tag at a time"?

**Comment by YuriDevAT** [comment]
I would even go simpler with: "Enter a tag", or "Enter an HTML tag"
