### ISSUE TITLE
[FEATURE] Progress bar

### ISSUE THREAD

**Issue by YuriDevAT** [YurisCodingClub/html-tag-quiz#25]
### Description

For every right tag the user writes in the input field, a progress bar should show their progress.

**Calculation (if I am not mistaken - I am bad at math 😅 )**
Tags: 124
Max: 100%
Calc simplified: 100 x 1 / 124

### Additional information

💡 Usage of semantic HTML. Watch out for helpful aria attributes.

**Resources:**
- https://www.w3.org/WAI/ARIA/apg/patterns/meter/
- https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/progressbar_role
- https://dequeuniversity.com/library/aria/progress-bar-bounded

**Comment by CorinaMurg** [comment]
🙏
