### ISSUE TITLE
[FEATURE] ReadMe file

### ISSUE THREAD

**Issue by YuriDevAT** [YurisCodingClub/html-tag-quiz#29]
### Description

Currently, the readme file contains general information on how to fork the repository. Since this guide is used in every project and stays the same, it should be moved, e.g. to a support repo.

### Acceptance criteria

- [ ] Remove the "How to contribute" section
- [ ] Remove the "Where to go from here?" section
- [ ] Store these section in the general discussion for further usage https://github.com/orgs/YurisCodingClub/discussions/34

### Screenshots

![readme of the project showing the sections to be deleted](https://github.com/YurisCodingClub/html-tag-quiz/assets/54622834/75c465e1-08a9-44a3-9f7b-25eb0d61415b)

**Comment by Muskan2404** [comment]
I'd like to work on this. Please assign me this issue.

**Comment by YuriDevAT** [comment]
Sure @Muskan2404 please go ahead.

**Comment by Muskan2404** [comment]
Do you want me to create a separate repo for it and move the content there or should i just move it to the link you provided above?

**Comment by YuriDevAT** [comment]
Move it to the link provided (I guess as a comment beneath it) should be fine.

**Comment by Muskan2404** [comment]
Got it, thanks. Also, is there some kind of time limit under which you want the work to be done?

**Comment by YuriDevAT** [comment]
If you want to get a Hacktoberfest badge then before October 31st 😁

**Comment by Muskan2404** [comment]
Haha, yeah ofcourse. I meant would it be fine if submit the PR after 14 or 15 hours?

**Comment by YuriDevAT** [comment]
Sure, take your time!

**Comment by Muskan2404** [comment]
Thanks a lot!
