### ISSUE TITLE
[BUG] h1-h6 not added to list

### ISSUE THREAD

**Issue by YuriDevAT** [YurisCodingClub/html-tag-quiz#33]
### Description
When trying to add `h1`, `h2`, `h3`, `h4`, `h5`, `h6` to the list, they do not show up in the list.

### AC
I expect these tags to be added to the list.

### Local test

<img width="813" alt="Application does not add h to list" src="https://github.com/YurisCodingClub/html-tag-quiz/assets/54622834/c0e55c9c-3f28-465c-98b9-896379ae86c0">

### Additional information

👉🏽 **Reference:** in `index.js` the tags from the [w3schools tag list](https://www.w3schools.com/tags/default.asp) are used. These tags are part of the list.
<img width="940" alt="w3schools-tag-list" src="https://github.com/YurisCodingClub/html-tag-quiz/assets/54622834/21e60599-2aa2-406e-8889-c131c357ae58">

💡 **Note:** They are not part of the [MDN tags list](https://developer.mozilla.org/en-US/docs/Web/HTML/Element), which seems not quite right for me since these are different tags.
<img width="940" alt="mdn-tag-list" src="https://github.com/YurisCodingClub/html-tag-quiz/assets/54622834/4cf65622-3a36-484a-a371-a218e763982a">

**Comment by CorinaMurg** [comment]
I also found it strange that MDN included only `h1` under their HTML elements list. It's probably just to be succinct.  Because if one clicks on `h1` then the description talks about the entire set of headings and their properties.

**Comment by YuriDevAT** [comment]
Right, good observation. I personally would prefer (and expect) them to be part of the list. We can also create a list out of these two to contain each element!

**Comment by YuriDevAT** [comment]
We can also add a note somewhere on the side (or as part of the hint) which says that the list contains all elements found in w3schools and MDN combained, e.g.

**Comment by CorinaMurg** [comment]
The list we are using now has all the 124 W3 tags (including all the headings). I used the MDN as a control list. (The tags.js file shows the difference between the two.)

Fixing the regex will take care of the bug, but maybe it's worth looking at the two lists again and see what extra tags the MDN list has and include them as well.

Happy to readjust the issue if we want to deal with all aspects of the tags list at once.

**Comment by CorinaMurg** [comment]
It does not let me update this issue (since you created it) so I will resolve it as it is now, and will create another one that deals with combining the two lists.
