### ISSUE TITLE
[BUG] Missing document title element

### ISSUE THREAD

**Issue by CorinaMurg** [YurisCodingClub/html-tag-quiz#39]
### Description
As a sighted user, I rely on the `title` element to quickly identify the purpose of a page. The content of the title element is displayed in the browser tab or window title bar and helps me identify and switch between open pages/tabs.

As a screen reader user, the `title` of a page will be announce when navigating to it, and it provides me with an immediate overview of the page’s content.

### Acceptance Criteria (AC)
- [ ] The `title` element is placed within the `head` section of the HTML document.
- [ ] There is only one title element per HTML document.
- [ ] The title contains text relevant to the content of the page. 

### Additional information

Useful link: [MDN Documentation on title element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/title)

**Comment by Galbrush** [comment]
Hi, could I work on this?

**Comment by YuriDevAT** [comment]
Sure @Galbrush happy to have you contributing to the project 🚀
