### ISSUE TITLE
[BUG] Missing label for input element

### ISSUE THREAD

**Issue by CorinaMurg** [YurisCodingClub/html-tag-quiz#40]
### Description

As a user I want to understand what data I should enter in the input field. 
<br>Each input should have a label that provides information about the input. This also helps users of assistive technologies identify the purpose of the input.

### Acceptance Criteria (AC)
- [ ] Provide a `label` for the existing input element.
- [ ] The label wraps the input OR contains a `for` attribute attached to the `id` of the input.
- [ ] If the label description is very short, provide a more descriptive `aria label` attribute to help screen reader users.

### Additional information

Useful link: [MDN documentation on label element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label)

**Comment by Bashamega** [comment]
Please assign me
