### ISSUE TITLE
[UPDATE] <Update tags data>

### ISSUE THREAD

**Issue by CorinaMurg** [YurisCodingClub/html-tag-quiz#49]
### Description

Currently, the app uses the tags data from the W3 website. The data is stored in an array that contains 124 tags, including deprecated ones. Compared to the tags list provided by MDN, there are several tags included in the MDN list but missing from the W3 list.

We need to combine the tags from both lists. We also want to make available to users (maybe when clicking on the tag's name) the following information about each tag:
- a description 
- whether or not the tag is deprecated
- whether or not it has specific semantic importance

Having all this data available will allow for a lot more flexibility when deciding about certain features of the app. For example, we could allow users to exclude the deprecated tags from the quiz.

### Acceptance Criteria
- [ ] Combine tags data from W3 and MDN
- [ ] Stored the data in an object with each key representing a tag name, and the value representing extra info about the tag
- [ ] The value of each key will contain: 1) a description of the tag 2) whether the tag is deprecated or not 3) whether the tag has specific semantic importance

**Comment by CorinaMurg** [comment]
The goal for this issue initially was to just update the tags data. After looking again at the W3 page and noticing the tags are ordered in a two-column format, with tag names in the first column, and tag descriptions in the second column, I realized we can easily use that to create an object instead of an array to store the data. 

We might decide along the way that we do not want to use all the info, but since we have to rethink the entire set of data, it's a good opportunity to include other tag details we might use in the future.

**Comment by YuriDevAT** [comment]
I like that idea. Maybe we could add a link to the MDN tag for further information, or even surround the tag in an `<a>` tag as a child of the current `<li>` - future thought. Either way, your suggestion to create an object seems like it comes with a lot of advantages!
