### ISSUE TITLE
[FEATURE] Create an input field

### ISSUE THREAD

**Issue by YuriDevAT** [YurisCodingClub/html-tag-quiz#5]
### Description

As a user I want to see an input field of type text where I can write into it and click a submit button which saves the input to localStorage as well as under the input field.

## Acceptance criteria

- Create a `<form>` with an `<input type="text">` and a `<button type="submit">` in the `index.html` file
- Create a **submit function** in the `index.js file` which saves the input to localStorage as well as showing it under the form  as a list
- No styling

### Additional information

If you are not familiar with localStorage yet, it is fine to not implement the functionality yet. I will migrate it to another issue later on.

**Comment by Sakshi-75** [comment]
Hi @YuriDevAT ,
Can I work on this?

**Comment by YuriDevAT** [comment]
Sure, go for it @Sakshi-75 🙂

**Comment by Sakshi-75** [comment]
Hi @YuriDevAT ,
I've raised a PR, please review it.

**Comment by Sakshi-75** [comment]
Hi @YuriDevAT can you please review the PR I raised? Thanks!

**Comment by Sakshi-75** [comment]
Hi @YuriDevAT , I've addressed all your comments. Can you review it again please? Thanks!
