### ISSUE TITLE
[BUG]Document type missing in index.html

### ISSUE THREAD

**Issue by YuriDevAT** [YurisCodingClub/html-tag-quiz#7]
### Description

As a developer I want to find the html code starting with a doctype

**Acceptance Criteria (AC)**
- [ ] Doctype declared in line 1

**Comment by kunalaudichya02** [comment]
assign me!

**Comment by Abdullahqasim75** [comment]
I want to work on this please

**Comment by saffi-786** [comment]
Hey @YuriDevAT I have raised a PR #13 
Can you please review it.

**Comment by shreyanshig** [comment]
Can you assign this task to me?
