### ISSUE TITLE
[BUG]Update list of html tags

### ISSUE THREAD

**Issue by YuriDevAT** [YurisCodingClub/html-tag-quiz#9]
### Description

In the index.js file is a const holding html tags. This list is incomplete and there are spelling errors.

**Acceptance Criteria (AC)**
- [ ] All tags are written correctly
- [ ] All tag strings only consist of words, no open close arrows
- [ ] All html tags are in the list, current and outdated

### Additional information

Useful link: https://www.w3schools.com/tags/default.asp

**Comment by kunalaudichya02** [comment]
I'll do that!

**Comment by CorinaMurg** [comment]
Is someone working on this issue already? If not, I am interested!

**Comment by YuriDevAT** [comment]
Please go ahead @CorinaMurg 🚀
